image: docker:stable-git

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  BASEIMAGE: registry.gitlab.com/thekesolutions/dspace

before_script:
  - docker login -u $PAUSER -p $PATOKEN registry.gitlab.com

build:
  stage: build
  script:
    - git clone -b $REF_BRANCH --single-branch https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/thekesolutions/Dspace.git dspace-src
    - mkdir m2-repo
    - echo "$BASEIMAGE/$REF_NAME:$REF_SHA $BASEIMAGE/$REF_NAME:$REF_TAG $BASEIMAGE/$REF_NAME:latest"
    - docker pull $BASEIMAGE/$REF_NAME:latest 
    - docker build --cache-from $BASEIMAGE/$REF_NAME:latest -t $BASEIMAGE/$REF_NAME:$REF_SHA -t $BASEIMAGE/$REF_NAME:$REF_TAG -t $BASEIMAGE/$REF_NAME:latest -f Dockerfile.prod .
    - docker push $BASEIMAGE/$REF_NAME:$REF_SHA
    - docker push $BASEIMAGE/$REF_NAME:$REF_TAG
    - docker push $BASEIMAGE/$REF_NAME:latest
  only:
    variables:
      - $REF_BRANCH
