image: docker:stable-git

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  BASEIMAGE: gitlab.com/thekesolutions/Dspace/$REF_BRANCH
  CONTAINER_TEST_IMAGE: $BASEIMAGE:$REF_COMMIT
  CONTAINER_RELEASE_IMAGE: $BASEIMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.com

build:
  stage: build
  script:
    - git clone -b $REF_BRANCH --single-branch https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/thekesolutions/Dspace.git dspace-src
    - mkdir m2-repo
    - docker build --pull -t CONTAINER_TEST_IMAGE -t CONTAINER_RELEASE_IMAGE -f Dockerfile.prod .
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    variables:
      - $REF_BRANCH
